version: "3.8"
services:
  db:
    image: mysql:8.0.33
    container_name: customer-registration-mysql
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: user-docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: customer-registration
    ports:
      - "3306:3306"
    networks:
      - customer-registration-network

  api-customer-registration:
    image: augustomarques/customer-registration
    container_name: customer-registration-app
    build: .
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user-docker
      DB_PASSWORD: docker
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    networks:
      - customer-registration-network

networks:
  customer-registration-network:
    driver: bridge
