name: CI

on:
  push:
    branches: [ "!main" ]

jobs:
  unit-test:
    uses: ./.github/workflows/unit-test.yml

  integration-test:
    needs: unit-test
    uses: ./.github/workflows/integration-test.yml

  sonarcube:
    needs: integration-test
    uses: ./.github/workflows/sonarcube.yml
    secrets: inherit
