name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  test-code-quality:
    uses: ./.github/workflows/commons/tests.yml
    secrets: inherit

  deploy:
    needs: test-code-quality
    uses: ./.github/workflows/commons/deploy.yml
    secrets: inherit
